import { business } from "@/lib/data";
import { env } from "@/lib/env";

type PdfField = { label: string; value: string | number | null | undefined };
type PdfSection = { title: string; fields?: PdfField[]; lines?: string[] };
type PdfOptions = {
  title: string;
  reference: string;
  subtitle?: string;
  status?: string;
  sections: PdfSection[];
  totals?: PdfField[];
  footerNote?: string;
};

function escapePdfText(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)").replace(/\r?\n/g, " ");
}

function fmt(value: string | number | null | undefined) {
  if (value === null || value === undefined || value === "") return "-";
  return String(value);
}

function wrap(value: string, max = 82) {
  const words = value.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > max && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  }
  if (current) lines.push(current);
  return lines.length ? lines : ["-"];
}

export function moneyLine(label: string, value: number) {
  return { label, value: `GBP ${value.toFixed(2)}` };
}

export function brandedPdf(options: PdfOptions) {
  const pages: string[][] = [];
  let content: string[] = [];
  let y = 0;

  function command(line: string) {
    content.push(line);
  }

  function text(value: string, x: number, atY: number, size = 10, bold = false) {
    command("BT");
    command(`${bold ? "/F2" : "/F1"} ${size} Tf`);
    command(`${x} ${atY} Td`);
    command(`(${escapePdfText(value)}) Tj`);
    command("ET");
  }

  function startPage() {
    if (content.length) pages.push(content);
    content = [];
    command("0.05 0.09 0.12 rg 0 770 595 72 re f");
    command("0.35 0.70 0.13 rg 0 766 595 4 re f");
    text("LME Pest Solutions", 42, 812, 20, true);
    text("Professional pest control across Manchester and the North West", 42, 792, 9);
    text(business.phone, 430, 812, 10, true);
    text(env.EMAIL_FROM || "info@lmepestsolutions.co.uk", 430, 795, 9);
    y = 735;
  }

  function ensure(space = 36) {
    if (y - space < 72) startPage();
  }

  function section(title: string) {
    ensure(52);
    command("0.35 0.70 0.13 rg 42 " + (y - 5) + " 120 2 re f");
    text(title, 42, y, 13, true);
    y -= 24;
  }

  function field(label: string, value: string | number | null | undefined) {
    const lines = wrap(fmt(value), labelWidth(label));
    lines.forEach((line, index) => {
      ensure(18);
      if (index === 0) text(`${label}:`, 42, y, 9, true);
      text(line, 170, y, 9);
      y -= 15;
    });
  }

  function labelWidth(label: string) {
    return Math.max(45, 92 - Math.floor(label.length / 2));
  }

  startPage();
  text(options.title, 42, y, 24, true);
  if (options.status) text(options.status, 430, y + 2, 11, true);
  y -= 25;
  text(options.subtitle || options.reference, 42, y, 11);
  y -= 28;

  section("Document Details");
  field("Reference", options.reference);
  field("Generated", new Date().toLocaleString("en-GB"));

  for (const item of options.sections) {
    section(item.title);
    for (const row of item.fields || []) field(row.label, row.value);
    for (const line of item.lines || []) {
      for (const wrapped of wrap(line, 92)) {
        ensure(18);
        text(wrapped, 42, y, 9);
        y -= 15;
      }
    }
  }

  if (options.totals?.length) {
    section("Totals");
    for (const row of options.totals) field(row.label, row.value);
  }

  if (options.footerNote) {
    section("Notes");
    for (const line of wrap(options.footerNote, 92)) {
      ensure(18);
      text(line, 42, y, 9);
      y -= 15;
    }
  }

  text("Generated by the LME Pest Solutions platform", 42, 42, 8);
  pages.push(content);

  const objects: string[] = [
    "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
    `2 0 obj << /Type /Pages /Kids [${pages.map((_, index) => `${5 + index * 2} 0 R`).join(" ")}] /Count ${pages.length} >> endobj`,
    "3 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
    "4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj",
  ];

  pages.forEach((page, index) => {
    const pageObject = 5 + index * 2;
    const contentObject = pageObject + 1;
    const stream = page.join("\n");
    objects.push(`${pageObject} 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentObject} 0 R >> endobj`);
    objects.push(`${contentObject} 0 obj << /Length ${Buffer.byteLength(stream)} >> stream\n${stream}\nendstream endobj`);
  });

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  for (const object of objects) {
    offsets.push(Buffer.byteLength(pdf));
    pdf += `${object}\n`;
  }
  const xref = Buffer.byteLength(pdf);
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets.slice(1)) pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(pdf);
}

